# Generated by Django 6.0.3 on 2026-03-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='choice',
            name='username',
            field=models.CharField(default='testuser', max_length=100),
            preserve_default=False,
        ),
    ]
